dist: xenial
language: cpp
compiler: clang
install:
- pip install conan
- conan user
script:
- conan install .
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T ip_filter2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ubluer-sys:$BINTRAY_API_KEY "https://api.bintray.com/content/bluersys/CPP/project_5_bin/$TRAVIS_BUILD_NUMBER/ip_filter2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
